# Generated by Django 5.1.2 on 2025-03-09 23:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trip_options_alter_vehicle_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='triprating',
            options={},
        ),
        migrations.AlterModelOptions(
            name='triprequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_read_bfd411_idx',
        ),
        migrations.RemoveIndex(
            model_name='triprequest',
            name='core_tripre_status_dfba42_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationrequest',
            name='core_verifi_status_610efc_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='fleet',
        ),
        migrations.AddField(
            model_name='booking',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='license_doc',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='nida_doc',
            field=models.FileField(default=django.utils.timezone.now, upload_to='verification_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='user_type',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver')], default='passenger', max_length=20),
        ),
        migrations.AlterField(
            model_name='clan',
            name='members',
            field=models.ManyToManyField(related_name='clans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trip'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trip'),
        ),
    ]
